main:
  - name: nav.posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - name: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - name: nav.archives
    pageRef: /archives
    weight: 50
    params:
      icon: archive
  # - name: nav.about
    # pageRef: /about
    # weight: 60
    # params:
      # icon: about

# footer social link
social:
  - name: RSS
    url: https://clixtw.github.io/index.xml
    weight: 10
    params:
      icon: rss
  - name: Email
    url: mailto:a8aixy693@mozmail.com
    weight: 20
    params:
      icon: email

